export const CLIENT_MASTERLIST = [
  "Abraham Uy",
  "Adam Wells",
  "Agency VA LLC",
  "Aileen Escobia",
  "Alfredo Hilario",
  "Anthony Del Rosario",
  "Azyantech Corp.",
  "B-7 Amusement",
  "Bernardita Uy",
  "Bernarita Doria",
  "Bingo King Systems Plus",
  "Bobby Buenaventura",
  "CCT - Partnership",
  "CCT - Sole Prop",
  "CITCO - 5D BIM Prodigy",
  "CITCO - APC BV",
  "CITCO - MIPI",
  "CITCO - MSHPL",
  "CITCO - RIB iTWO Software",
  "CITCO - SEIT",
  "CITCO - SEITLAP",
  "CITCO - SEPH",
  "CITCO - SEPH/SEIT",
  "CITCO - Syniverse",
  "CITCO - WUFSHK",
  "CITCO - WUPSI",
  "CITCO - WUSPI",
  "D'Sheer Fabrics",
  "DFNN",
  "Domingo S. Guevara, Jr.",
  "Dredging International NV Phil Branch",
  "E&T Management Inc.",
  "EGT/TEG",
  "Elite Jinzai Marketing Services",
  "Encarnacion and Mariano Mallari",
  "Fort Senica",
  "Geobrugg Philippines",
  "Gilbert Burgos",
  "Guevent Investments Development Corp.",
  "Harly Pow",
  "Harry Hu",
  "Hilmarie Aggregates, OPC",
  "IEST",
  "Imelda de los Santos",
  "Jonathan Sanoy",
  "Juliet Langcay",
  "Kat Alcantara Sotto",
  "Kris Ysmael",
  "Kristian Favor",
  "Lee and Angie Shaddock",
  "Lourdes Aguirre",
  "Marty Franz Torralba",
  "Melania and Teresita",
  "Metro Iloilo",
  "Monfort Foundation",
  "Paulino Castro",
  "Pagent Growth Seed Kapital Holdings Inc.",
  "Premier Logistics",
  "Product Palace Inc.",
  "Radiant Bay",
  "Rebtrade International",
  "Reynaldo Colindres",
  "RJ Paguyo",
  "RPLAI - Brasbag Development Corp.",
  "RPLAI - Happy Hen Hatchery",
  "RPLAI - Havenbrook Properties",
  "RPLAI - Highridge Breeding Farms",
  "RPLAI - Riza Development Corp.",
  "RPLAI - Sunny and Scramble",
  "Rizal Poultry and Livestock Association, Inc.",
  "Rizal Poultry Corp.",
  "Rizal Poultry Group",
  "Rodolfo Tan",
  "Rolly De Guzman",
  "Romeo Alcantara",
  "Ron Largoza",
  "Rossana P. Cleofas",
  "S4Gaming S.L.",
  "Salud De Guzman",
  "STLAF - Partnership",
  "STLAF - Sole Prop",
  "Super Nova Powder Coating Company",
  "Tan Lato Reyes",
  "Tekvision Distribution Inc.",
  "The Ace Solutions",
  "Tirebiter Inc.",
  "TWEC, Inc.",
  "Virtue Edge Enterprise Inc.",
  "Waltermart Supermarkets, Inc.",
  "Xyza Favor",
  "XN Solutions, Inc.",
  "Yanmar - Global",
  "Yanmar - YAG",
  "Yanmar - YIS",
  "Yanmar - YISS",
  "Yanmar Philippines Corp.",
  "Zoomanity Group Corp.",
].sort();

export const ACCOUNT_CHOICES = [
  "Repair and Maintenance",
  "Transportation and Travel (Non-Billable)",
  "Transportation and Travel (Billable)",
  "Fuel and Oil (Non-Billable)",
  "Parking Expenses (Non-Billable)",
  "Miscellaneous Expense (Non-Billable)",
  "Miscellaneous Expense (Billable)",
  "Telephone Expense",
  "Courier Expense (Non-Billable)",
  "Courier Expense (Billable)",
  "Office Supplies Expense",
  "Bank Charges",
  "Other Expenses"
];
